name: Fragment
favicon: null
layout_spectrum: 0.78604
typography_spectrum: 0.42778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#142129'
    - '#2b4d68'
    - '#d7cdcb'
    - '#7691ad'
    - '#c6b3ad'
  brandStrength: 0.8296288456767797
  lightness: 0.875
  saturation: 0.7555026668123901
  rhythmicContrast: 0.5599334503058344
purpose: []
