name: Fragment
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303030'
    - '#ffffff'
    - '#236aa8'
    - '#226aa8'
    - '#2c3e4e'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0
purpose: []
