name: Fragment
favicon: null
layout_spectrum: 0.9976
typography_spectrum: 0.42778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#142129'
    - '#2b4d68'
    - '#d7cdcb'
    - '#7691ad'
    - '#c6b3ad'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0
purpose: []
